version: "3.7"
services:
  vault:
    image: vault:1.8.12
    environment:
      - SKIP_SETCAP=true
    volumes:
      - ./vault-init/config.hcl:/config/config.hcl
      - ./vault-data:/vault
    command: vault server -config=/config
  vault-init:
    image: vault-init
    build: ./vault-init
    depends_on:
      - vault
    volumes:
      - ./vault-data:/vault-data
  vault-ui:
    image: djenriquez/vault-ui
    ports:
      - "8000:8000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
    depends_on:
      vault-init:
        condition: service_completed_successfully
  example:
    image: bash:5.1
    depends_on:
      vault-init:
        condition: service_completed_successfully
    volumes:
      - ./vault-data:/vault-data
    command: bash -c 'ROOT_TOKEN=`cat /vault-data/token.txt`; echo "Root token $$ROOT_TOKEN"'

